import Navbar from "./components/common/Navbar";
import { ColorProvider } from "./context/color_context";
import "./globals.css";
import { Roboto_Serif } from "next/font/google";

const roboto = Roboto_Serif({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Islam Aboamh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {/* <Navbar /> */}
        <ColorProvider>{children}</ColorProvider>
      </body>
    </html>
  );
}
